-- Apply after the account migrations. All gold cards remain locked: no events are inserted.
begin;
create table public.album_seasons(id text primary key,name text not null);
create table public.album_sets(season_id text references public.album_seasons(id),set_number smallint check(set_number between 1 and 15),name text not null,primary key(season_id,set_number));
create table public.album_cards(season_id text,card_number smallint,name text not null,stars smallint not null check(stars between 1 and 5),gold boolean not null, set_number smallint not null,primary key(season_id,card_number),foreign key(season_id,set_number) references public.album_sets);
create table public.card_inventory(user_id uuid references auth.users(id) on delete cascade,season_id text,card_number smallint,quantity integer not null check(quantity between 0 and 999),updated_at timestamptz not null default now(),primary key(user_id,season_id,card_number),foreign key(season_id,card_number) references public.album_cards);
create table public.album_priorities(user_id uuid references auth.users(id) on delete cascade,season_id text,set_number smallint,priority smallint not null default 2 check(priority between 1 and 3),primary key(user_id,season_id,set_number),foreign key(season_id,set_number) references public.album_sets);
create table public.album_trade_preferences(user_id uuid references auth.users(id) on delete cascade,season_id text references public.album_seasons,accept_equal boolean not null default true,accept_up boolean not null default false,accept_down boolean not null default false,accept_any boolean not null default false,primary key(user_id,season_id));
create table public.gold_exchange_events(id bigint generated always as identity primary key,season_id text not null references public.album_seasons,starts_at timestamptz not null,ends_at timestamptz not null,published boolean not null default false,check(ends_at>starts_at));
alter table public.album_seasons enable row level security;alter table public.album_sets enable row level security;alter table public.album_cards enable row level security;alter table public.card_inventory enable row level security;alter table public.album_priorities enable row level security;alter table public.album_trade_preferences enable row level security;alter table public.gold_exchange_events enable row level security;
revoke all on public.album_seasons,public.album_sets,public.album_cards,public.card_inventory,public.album_priorities,public.album_trade_preferences,public.gold_exchange_events from public,anon,authenticated;
grant select on public.album_seasons,public.album_sets,public.album_cards,public.gold_exchange_events to anon,authenticated;
grant select on public.card_inventory to authenticated;
grant select,insert,update on public.album_priorities,public.album_trade_preferences to authenticated;
create policy seasons_read on public.album_seasons for select to anon,authenticated using(true);
create policy sets_read on public.album_sets for select to anon,authenticated using(true);
create policy cards_read on public.album_cards for select to anon,authenticated using(true);
create policy exchange_read on public.gold_exchange_events for select to anon,authenticated using(published);
create policy inventory_read_own on public.card_inventory for select to authenticated using((select auth.uid())=user_id);
create policy priorities_own on public.album_priorities for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
create policy trade_preferences_own on public.album_trade_preferences for all to authenticated using((select auth.uid())=user_id) with check((select auth.uid())=user_id);
-- Only this narrow RPC may change quantities. It cannot write another user's inventory.
create function public.album_adjust_quantity(p_season text,p_card smallint,p_delta integer)
returns table(quantity integer,updated_at timestamptz) language plpgsql security definer set search_path=pg_catalog as $$
declare uid uuid := auth.uid();old_qty integer;new_qty integer;
begin
 if uid is null then raise exception 'Login required'; end if;
 if p_delta is null or p_delta not in (-1,1) then raise exception 'Only +1 or -1 allowed';end if;
 if not exists(select 1 from public.album_cards c where c.season_id=p_season and c.card_number=p_card) then raise exception 'Unknown card';end if;
 perform pg_advisory_xact_lock(hashtextextended(uid::text||':'||p_season||':'||p_card::text,0));
 select i.quantity into old_qty from public.card_inventory i where i.user_id=uid and i.season_id=p_season and i.card_number=p_card;
 old_qty:=coalesce(old_qty,0);new_qty:=greatest(0,least(999,old_qty+p_delta));
 if new_qty<>old_qty then
 insert into public.card_inventory as i(user_id,season_id,card_number,quantity,updated_at) values(uid,p_season,p_card,new_qty,now()) on conflict(user_id,season_id,card_number) do update set quantity=excluded.quantity,updated_at=now();
 end if;
 return query select coalesce(i.quantity,0),i.updated_at from (select 1) x left join public.card_inventory i on i.user_id=uid and i.season_id=p_season and i.card_number=p_card;
end $$;
revoke all on function public.album_adjust_quantity(text,smallint,integer) from public,anon;
grant execute on function public.album_adjust_quantity(text,smallint,integer) to authenticated;
create function public.album_exchange_status(p_season text) returns boolean language sql stable security invoker set search_path=pg_catalog as $$select exists(select 1 from public.gold_exchange_events e where e.season_id=p_season and e.published and now()>=e.starts_at and now()<e.ends_at)$$;
revoke all on function public.album_exchange_status(text) from public;
grant execute on function public.album_exchange_status(text) to anon,authenticated;
create function public.album_tradeable_inventory(p_season text) returns table(card_number smallint,duplicates integer,updated_at timestamptz) language sql stable security invoker set search_path=pg_catalog as $$select i.card_number,i.quantity-1,i.updated_at from public.card_inventory i join public.album_cards c using(season_id,card_number) where i.user_id=auth.uid() and i.season_id=p_season and i.quantity>=2 and (not c.gold or public.album_exchange_status(p_season))$$;
revoke all on function public.album_tradeable_inventory(text) from public,anon;
grant execute on function public.album_tradeable_inventory(text) to authenticated;
-- Catalog seed follows. No Gold Exchange dates are assumed.
insert into public.album_seasons values('autumn-tales','Autumn Tales');
insert into public.album_sets values('autumn-tales',1,'Solpear Set');
insert into public.album_sets values('autumn-tales',2,'Sparkrow Set');
insert into public.album_sets values('autumn-tales',3,'Droppit Set');
insert into public.album_sets values('autumn-tales',4,'Taptail Set');
insert into public.album_sets values('autumn-tales',5,'Voltkit Set');
insert into public.album_sets values('autumn-tales',6,'Ringtail Set');
insert into public.album_sets values('autumn-tales',7,'Maskfry Set');
insert into public.album_sets values('autumn-tales',8,'Tindercub Set');
insert into public.album_sets values('autumn-tales',9,'Punchimp Set');
insert into public.album_sets values('autumn-tales',10,'Manteeny Set');
insert into public.album_sets values('autumn-tales',11,'Flameow Set');
insert into public.album_sets values('autumn-tales',12,'Kittazap Set');
insert into public.album_sets values('autumn-tales',13,'Cheerling Set');
insert into public.album_sets values('autumn-tales',14,'Momopo Set');
insert into public.album_sets values('autumn-tales',15,'Sparkit Set');
insert into public.album_cards values('autumn-tales',1,'Autumn Arrives',1,false,1);
insert into public.album_cards values('autumn-tales',2,'Chestnut Circle',1,false,1);
insert into public.album_cards values('autumn-tales',3,'Ripened Pear',1,false,1);
insert into public.album_cards values('autumn-tales',4,'Autumn Haul',1,false,1);
insert into public.album_cards values('autumn-tales',5,'Pear Scream',1,false,1);
insert into public.album_cards values('autumn-tales',6,'Fresh Stock',1,false,1);
insert into public.album_cards values('autumn-tales',7,'Copycats',1,false,1);
insert into public.album_cards values('autumn-tales',8,'Cozy Pear Autumn',1,false,1);
insert into public.album_cards values('autumn-tales',9,'Berry Picnic',2,false,1);
insert into public.album_cards values('autumn-tales',10,'Paws Off!',1,false,2);
insert into public.album_cards values('autumn-tales',11,'Leafy Nest',1,false,2);
insert into public.album_cards values('autumn-tales',12,'Filter On',1,false,2);
insert into public.album_cards values('autumn-tales',13,'Shoulder Perch',1,false,2);
insert into public.album_cards values('autumn-tales',14,'The Admirer',1,false,2);
insert into public.album_cards values('autumn-tales',15,'Masterpiece',1,false,2);
insert into public.album_cards values('autumn-tales',16,'Sugar Rush',1,false,2);
insert into public.album_cards values('autumn-tales',17,'Take Cover!',2,false,2);
insert into public.album_cards values('autumn-tales',18,'Give it Back!',2,false,2);
insert into public.album_cards values('autumn-tales',19,'Lake Reflection',1,false,3);
insert into public.album_cards values('autumn-tales',20,'Swinging High',1,false,3);
insert into public.album_cards values('autumn-tales',21,'Autumn Outing',1,false,3);
insert into public.album_cards values('autumn-tales',22,'Shroom Magic',1,false,3);
insert into public.album_cards values('autumn-tales',23,'Hare Hazard',1,false,3);
insert into public.album_cards values('autumn-tales',24,'Drip Drop',1,false,3);
insert into public.album_cards values('autumn-tales',25,'Sky Siesta',2,false,3);
insert into public.album_cards values('autumn-tales',26,'Drifting Dream',2,false,3);
insert into public.album_cards values('autumn-tales',27,'Lunar Leap',3,false,3);
insert into public.album_cards values('autumn-tales',28,'Snake Scarf',1,false,4);
insert into public.album_cards values('autumn-tales',29,'Knock Knock!',1,false,4);
insert into public.album_cards values('autumn-tales',30,'Baguette Thief',1,false,4);
insert into public.album_cards values('autumn-tales',31,'Rain Watching',1,false,4);
insert into public.album_cards values('autumn-tales',32,'Tea Time',1,false,4);
insert into public.album_cards values('autumn-tales',33,'Just Yawning',2,false,4);
insert into public.album_cards values('autumn-tales',34,'Refined Tastes',2,false,4);
insert into public.album_cards values('autumn-tales',35,'Cobra Alert',2,false,4);
insert into public.album_cards values('autumn-tales',36,'Ginger Treats',3,false,4);
insert into public.album_cards values('autumn-tales',37,'Volt Strike',1,false,5);
insert into public.album_cards values('autumn-tales',38,'Among Leaves',1,false,5);
insert into public.album_cards values('autumn-tales',39,'Acorn Express',1,false,5);
insert into public.album_cards values('autumn-tales',40,'Photo Bomb',1,false,5);
insert into public.album_cards values('autumn-tales',41,'Windchaser',2,false,5);
insert into public.album_cards values('autumn-tales',42,'Hero''s Stance',2,false,5);
insert into public.album_cards values('autumn-tales',43,'Granny Wolf',2,false,5);
insert into public.album_cards values('autumn-tales',44,'Moonhowler',3,false,5);
insert into public.album_cards values('autumn-tales',45,'Heartfelt Gift',3,false,5);
insert into public.album_cards values('autumn-tales',46,'Big Catch',1,false,6);
insert into public.album_cards values('autumn-tales',47,'Hanging Decor',1,false,6);
insert into public.album_cards values('autumn-tales',48,'Boo!',1,false,6);
insert into public.album_cards values('autumn-tales',49,'Leaf Racer',2,false,6);
insert into public.album_cards values('autumn-tales',50,'Have a Bite',2,false,6);
insert into public.album_cards values('autumn-tales',51,'Moonlit Bandit',2,false,6);
insert into public.album_cards values('autumn-tales',52,'No Racoons',3,false,6);
insert into public.album_cards values('autumn-tales',53,'Heart Thief',3,false,6);
insert into public.album_cards values('autumn-tales',54,'Night Prowler',3,false,6);
insert into public.album_cards values('autumn-tales',55,'Strange Forms',1,false,7);
insert into public.album_cards values('autumn-tales',56,'Boat Practice',1,false,7);
insert into public.album_cards values('autumn-tales',57,'Danger Ahead',2,false,7);
insert into public.album_cards values('autumn-tales',58,'Need Something?',2,false,7);
insert into public.album_cards values('autumn-tales',59,'Bath Buddy',2,false,7);
insert into public.album_cards values('autumn-tales',60,'Odd Flavors',2,false,7);
insert into public.album_cards values('autumn-tales',61,'Proper Dapper',3,false,7);
insert into public.album_cards values('autumn-tales',62,'Gloomy Tunes',3,false,7);
insert into public.album_cards values('autumn-tales',63,'Deepsea Visitor',4,true,7);
insert into public.album_cards values('autumn-tales',64,'Fluttery Friend',1,false,8);
insert into public.album_cards values('autumn-tales',65,'Prance & Prowl',1,false,8);
insert into public.album_cards values('autumn-tales',66,'Stop & Sniff',2,false,8);
insert into public.album_cards values('autumn-tales',67,'Roaring Rouse',2,false,8);
insert into public.album_cards values('autumn-tales',68,'Tiger Bae',2,false,8);
insert into public.album_cards values('autumn-tales',69,'Waterfall Wisdom',3,false,8);
insert into public.album_cards values('autumn-tales',70,'Distant Dreams',3,false,8);
insert into public.album_cards values('autumn-tales',71,'Pumpkin Rampage',4,false,8);
insert into public.album_cards values('autumn-tales',72,'Bonfire Night',4,true,8);
insert into public.album_cards values('autumn-tales',73,'Letting Loose',1,false,9);
insert into public.album_cards values('autumn-tales',74,'Spicy Spin',2,false,9);
insert into public.album_cards values('autumn-tales',75,'No Thoughts',2,false,9);
insert into public.album_cards values('autumn-tales',76,'Moonfisher',2,false,9);
insert into public.album_cards values('autumn-tales',77,'Tree Slide',3,false,9);
insert into public.album_cards values('autumn-tales',78,'Prank Partners',3,false,9);
insert into public.album_cards values('autumn-tales',79,'Cloud Gazing',3,false,9);
insert into public.album_cards values('autumn-tales',80,'This You?',4,true,9);
insert into public.album_cards values('autumn-tales',81,'Monkey King',4,false,9);
insert into public.album_cards values('autumn-tales',82,'Face Off',2,false,10);
insert into public.album_cards values('autumn-tales',83,'Total Devotion',2,false,10);
insert into public.album_cards values('autumn-tales',84,'Many Options',2,false,10);
insert into public.album_cards values('autumn-tales',85,'Moonlit Lake',3,false,10);
insert into public.album_cards values('autumn-tales',86,'Orchid Bloom',3,false,10);
insert into public.album_cards values('autumn-tales',87,'Petal Slash',3,false,10);
insert into public.album_cards values('autumn-tales',88,'Floral Crown',4,false,10);
insert into public.album_cards values('autumn-tales',89,'Tea Party',4,false,10);
insert into public.album_cards values('autumn-tales',90,'Flower Haven',5,true,10);
insert into public.album_cards values('autumn-tales',91,'Meal Misfortune',2,false,11);
insert into public.album_cards values('autumn-tales',92,'Dinner Dilemma',2,false,11);
insert into public.album_cards values('autumn-tales',93,'Feline Bonding',3,false,11);
insert into public.album_cards values('autumn-tales',94,'Sunset Field',3,false,11);
insert into public.album_cards values('autumn-tales',95,'Midnight Magic',3,false,11);
insert into public.album_cards values('autumn-tales',96,'Wise Words',4,true,11);
insert into public.album_cards values('autumn-tales',97,'Maple Meeting',4,false,11);
insert into public.album_cards values('autumn-tales',98,'Idle Paws',4,true,11);
insert into public.album_cards values('autumn-tales',99,'Day''s Work',5,false,11);
insert into public.album_cards values('autumn-tales',100,'Low Energy',2,false,12);
insert into public.album_cards values('autumn-tales',101,'Desk Job',3,false,12);
insert into public.album_cards values('autumn-tales',102,'Fish Watching',3,false,12);
insert into public.album_cards values('autumn-tales',103,'Knitting Time',3,false,12);
insert into public.album_cards values('autumn-tales',104,'Comfort Food',4,false,12);
insert into public.album_cards values('autumn-tales',105,'Splendid Night',4,false,12);
insert into public.album_cards values('autumn-tales',106,'Festive Duty',4,true,12);
insert into public.album_cards values('autumn-tales',107,'Kitty Mambo',5,false,12);
insert into public.album_cards values('autumn-tales',108,'Hallowed Night',5,true,12);
insert into public.album_cards values('autumn-tales',109,'Cheer Up',3,false,13);
insert into public.album_cards values('autumn-tales',110,'Sweet Moments',3,false,13);
insert into public.album_cards values('autumn-tales',111,'Center Stage',3,false,13);
insert into public.album_cards values('autumn-tales',112,'Onward Together',4,false,13);
insert into public.album_cards values('autumn-tales',113,'Make a Wish',4,true,13);
insert into public.album_cards values('autumn-tales',114,'Novice Witch',4,true,13);
insert into public.album_cards values('autumn-tales',115,'Shroom Slumber',5,false,13);
insert into public.album_cards values('autumn-tales',116,'Starlit Ride',5,false,13);
insert into public.album_cards values('autumn-tales',117,'Co-Star',5,true,13);
insert into public.album_cards values('autumn-tales',118,'Beauty Sleep',3,false,14);
insert into public.album_cards values('autumn-tales',119,'Today''s Outfit',3,false,14);
insert into public.album_cards values('autumn-tales',120,'My Little Hippo',4,false,14);
insert into public.album_cards values('autumn-tales',121,'No Crowd Needed',4,true,14);
insert into public.album_cards values('autumn-tales',122,'Momopo Rage',4,false,14);
insert into public.album_cards values('autumn-tales',123,'Classy Bath',4,true,14);
insert into public.album_cards values('autumn-tales',124,'Graceful Steps',5,false,14);
insert into public.album_cards values('autumn-tales',125,'Come Play!',5,true,14);
insert into public.album_cards values('autumn-tales',126,'Washing Up',5,false,14);
insert into public.album_cards values('autumn-tales',127,'Creative Spark',3,false,15);
insert into public.album_cards values('autumn-tales',128,'Fox in the Box',3,false,15);
insert into public.album_cards values('autumn-tales',129,'Nap Buddies',4,false,15);
insert into public.album_cards values('autumn-tales',130,'Trick or Treat!',4,false,15);
insert into public.album_cards values('autumn-tales',131,'Patience Pays',4,true,15);
insert into public.album_cards values('autumn-tales',132,'Signature Move',5,false,15);
insert into public.album_cards values('autumn-tales',133,'Old Tricks',5,false,15);
insert into public.album_cards values('autumn-tales',134,'Try a Bite',5,true,15);
insert into public.album_cards values('autumn-tales',135,'Grand Entrance',5,true,15);
commit;
