begin;
alter table public.album_trade_preferences drop constraint if exists album_trade_preferences_rarity_mode_check;
alter table public.album_trade_preferences add constraint album_trade_preferences_rarity_mode_check check(rarity_mode in ('Same Rarity','Flexible Rarity','Any Rarity','No Trading'));
create or replace function public.trade_card_available(p_season text,p_card smallint) returns boolean language sql stable security definer set search_path=pg_catalog as $$select exists(select 1 from public.album_cards c where c.season_id=p_season and c.card_number=p_card)$$;
create or replace function public.trade_accepts(p_user uuid,p_season text,give_star smallint,receive_star smallint) returns boolean language sql stable security definer set search_path=pg_catalog as $$select coalesce((select p.rarity_mode<>'No Trading' and (p.accept_any or (receive_star=give_star and p.accept_equal) or (receive_star=give_star+1 and p.accept_up) or (receive_star=give_star-1 and p.accept_down)) from public.album_trade_preferences p where p.user_id=p_user and p.season_id=p_season),receive_star=give_star)$$;
create or replace function public.trade_listings(p_season text,p_set integer default null,p_star integer default null,p_limit integer default 30,p_offset integer default 0) returns jsonb language sql stable security definer set search_path=pg_catalog as $$
with listings as (
 select p.user_id,p.game_id,p.display_name,p.avatar_url,
 (select max(i.updated_at) from public.card_inventory i where i.user_id=p.user_id and i.season_id=p_season and i.quantity>=2 and public.trade_card_available(p_season,i.card_number)) freshness,
 (select jsonb_agg(i.card_number order by i.card_number) from public.card_inventory i join public.album_cards c using(season_id,card_number) where i.user_id=p.user_id and i.season_id=p_season and i.quantity>=2 and public.trade_card_available(p_season,i.card_number) and (p_set is null or c.set_number=p_set) and (p_star is null or c.stars=p_star)) ft,
 (select coalesce(jsonb_agg(jsonb_build_object('give',a.card_number,'receive',b.card_number) order by a.card_number,b.card_number),'[]'::jsonb) from public.card_inventory yours join public.album_cards a on a.season_id=yours.season_id and a.card_number=yours.card_number cross join public.card_inventory theirs join public.album_cards b on b.season_id=theirs.season_id and b.card_number=theirs.card_number where yours.user_id=auth.uid() and exists(select 1 from public.profiles own where own.user_id=auth.uid() and own.game_id<>'') and yours.season_id=p_season and yours.quantity>=2 and theirs.user_id=p.user_id and theirs.season_id=p_season and theirs.quantity>=2 and public.trade_card_available(p_season,a.card_number) and public.trade_card_available(p_season,b.card_number) and (p_set is null or b.set_number=p_set) and (p_star is null or b.stars=p_star) and not exists(select 1 from public.card_inventory k where k.user_id=p.user_id and k.season_id=p_season and k.card_number=a.card_number and k.quantity>0) and not exists(select 1 from public.card_inventory k where k.user_id=auth.uid() and k.season_id=p_season and k.card_number=b.card_number and k.quantity>0) and public.trade_accepts(auth.uid(),p_season,a.stars,b.stars) and public.trade_accepts(p.user_id,p_season,b.stars,a.stars)) swaps
 from public.profiles p where p.trade_enabled and p.game_id<>'' and coalesce((select preferences.rarity_mode from public.album_trade_preferences preferences where preferences.user_id=p.user_id and preferences.season_id=p_season),'Same Rarity')<>'No Trading' and p.user_id is distinct from auth.uid()
),page as (select * from listings where ft is not null order by freshness desc,user_id limit least(50,greatest(1,p_limit)) offset greatest(0,p_offset))
select coalesce(jsonb_agg(jsonb_build_object('id',user_id,'uid',game_id,'name',display_name,'avatar',avatar_url,'updated_at',freshness,'ft',ft,'swaps',swaps) order by freshness desc,user_id),'[]'::jsonb) from page
$$;
create or replace function public.album_tradeable_inventory(p_season text) returns table(card_number smallint,duplicates integer,updated_at timestamptz) language sql stable security invoker set search_path=pg_catalog as $$select i.card_number,i.quantity-1,i.updated_at from public.card_inventory i where i.user_id=auth.uid() and i.season_id=p_season and i.quantity>=2 and coalesce((select p.rarity_mode from public.album_trade_preferences p where p.user_id=auth.uid() and p.season_id=p_season),'Same Rarity')<>'No Trading'$$;
commit;
